<?php
/**
 * Li3_twig: Two step Twig renderer for Lithium: the most rad php framework
 *
 * @copyright     Copyright 2010, Union of RAD (http://union-of-rad.org)
 * @license       http://opensource.org/licenses/bsd-license.php The BSD License
 */

namespace li3_twig\tests\mocks\template\view\adapter;

/**
 * Mock of a compiled template. These are autogenerated by twig normally
 *
 * @see http://twig-project.org
 * @author Raymond Julin <raymond.julin@gmail.com>
 */
class MockTemplate extends \li3_twig\template\view\adapter\Template {
    public function display(array $context, array $blocks = array()) {
        echo $this->getAttribute((isset($context['foo']) ? $context['foo'] : null), "bar", array(), "any");
    }

    public function getTemplateName() {
        return "mock.html.twig";
    }
}

